services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/mydatabase
    volumes:
      - .:/usr/src/app
    command: npm run start

  mongo:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
